name: artoon_3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/flags/english.png
    - assets/flags/arabic.png
    - assets/flags/spanish.png
    - assets/flags/french.png
    - assets/flags/german.png
    - assets/flags/portugal.png
    - assets/flags/korean.png
    - assets/flags/hindi.png
    - assets/icons/ai_art.png
    - assets/icons/ai_avatar.png
    - assets/icons/ai_enhance.png
    - assets/icons/face_me.png
    - assets/icons/text_to_image.png
    - assets/images/autumn_3d.png
    - assets/images/image.png
    - assets/images/banner.png
