name: artoon_7
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  http: ^1.2.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/flags/hindi.png
    - assets/icons/ai_avatar.png
    - assets/icons/ai_art.png
    - assets/icons/ai_enhance.png
    - assets/icons/face_me.png
    - assets/icons/text_to_image.png
    - assets/icons/woman.png
    - assets/icons/man.png
    - assets/images/image1.png
    - assets/images/banner.png

